version: 21
jobs:
- name: Remote Sync
  steps:
  - !PushRepository
    name: Remote Push
    remoteUrl: https://github.com/davidedpg10/GopherCloud.git
    userName: davidedpg10
    passwordSecret: gh_token
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
